import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import "../styles/index.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"main"}>
        <div className={"description"}>
          <p>
            Get started by editing&nbsp;
            <code className={"code"}>pages/index.js</code>
          </p>
          <div className="flex flex-col">
            <Link href="/test">test</Link>
            <Link href="/query">query</Link>
          </div>
        </div>
      </main>
    </>
  );
}
