import Head from "next/head";
import { Inter } from "@next/font/google";
import "../styles/index.module.css";
import Link from "next/link";
import { Button, Input, message } from "antd";
import FeatherIcon from "feather-icons-react";
import { useState } from "react";

const inter = Inter({ subsets: [ "latin" ] });

export default function Home() {
  const [ wallet, setWallet ] = useState("0xacD03D601e5bB1B275Bb94076fF46ED9D753435A");
  const isAddressValid = (address) => {
    const re = /^0x[a-fA-F0-9]{40}$/;
    return re.test(address);
  };
  return (
    <>
      <Head>
        <title>Optimism Wallet Tracker</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div className={"flex flex-col justify-center items-center gap-8"} style={{ height: 400 }}>
        <div className="flex gap-2">
          <img src="https://static.footprint.network/fp-chains/optimism.webp" style={{ width: 48, height: 48 }}/>
          <h1 className="text-5xl">Optimism Wallet Tracker</h1>
        </div>
        <Input value={wallet} size="large" placeholder="Input your wallet address" style={{ width: 480 }} onChange={(e) => {
          setWallet(e.target.value)
        }}/>
        <Link href={`/query?wallet=${wallet}`}>
          <Button className="flex justify-center items-center" size="large" style={{ width: 160 }}
                  icon={<FeatherIcon icon="search"/>} onClick={(event) => {
            if (isAddressValid(wallet)) {
              console.log('Address is correct, proceed with the action');
              // 在这里放置允许的操作
            } else {
              console.log('Access denied, address is not correct');
              // 在这里处理不允许的情况，比如显示错误消息
              event.preventDefault();
              message.error('Invalid address');
            }
          }}>Scan</Button>
        </Link>
        <Link className="underline" href="https://optimistic.etherscan.io/accounts" target="_blank">Top Account</Link>
      </div>
    </>
  );
}
